version: '3.9'
services:
  private_avito_api_executor:
    build:
      context: '.'
      dockerfile: services/private_avito_api_executor/Dockerfile
    command: poetry run python -m services.private_avito_api_executor.main
    restart: always
    ports:
      - "50051"
    environment:
      GRPC_SERVER_ADDR: "private_avito_api_executor:50051"
      AVITO_MAGIC_KEY: af0deccbgcgidddjgnvljitntccdduijhdinfgjgfjir
    volumes:
      - '.:/app'
  worker:
    build:
      context: '.'
    command: poetry run celery --app services.worker.app worker --loglevel INFO
    restart: always
    depends_on:
      - redis
      - rabbitmq
      - private_avito_api_executor
    environment:
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq"
      CELERY_RESULT_BACKEND: "redis://redis"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PRIVATE_AVITO_API_EXECUTOR_GRPC_SERVER_ADDR: "private_avito_api_executor:50051"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: db
      DB_PORT: 5433
    volumes:
      - '.:/app'
  amount_ads_observer:
    build:
      context: '.'
    command: poetry run uvicorn services.amount_ads_observer.main:app --host 0.0.0.0 --port 8000
    restart: always
    environment:
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: db
      DB_PORT: 5433
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq"
      CELERY_RESULT_BACKEND: "redis://redis"
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - db
      - worker
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db:/var/lib/postgresql/data
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6364:6379"
  rabbitmq:
    image: rabbitmq:3.10-alpine
    restart: always
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USERNAME}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"

volumes:
  db:
    driver: local